import React, { useState, useMemo, useEffect, useRef } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartsTooltip,
  Legend,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  LineChart,
  Line,
  AreaChart,
  Area,
} from "recharts";
import {
  LayoutDashboard,
  Factory,
  Users,
  FileText,
  Settings,
  Bell,
  Search,
  AlertTriangle,
  CheckCircle,
  DollarSign,
  Warehouse,
  MoreVertical,
  X,
  Filter,
  Map,
  Calendar,
  TrendingUp,
  Download,
  ChevronDown,
  Printer,
  Lock,
  Unlock,
  Share2,
  Copy,
  LogIn,
  Eye,
  Wrench,
  Plus,
  Tag,
  Clock,
  MapPin,
  CheckSquare,
  Edit3,
  Save,
  LifeBuoy,
  MessageSquare,
  Camera,
  Star,
  Image as ImageIcon,
  Upload,
  Zap,
  Droplets,
  FileWarning,
  PlayCircle,
  Trash2,
  GripVertical,
  BarChart2,
  PieChart as PieIcon,
  Maximize2,
  ArrowUpRight,
  ArrowDownRight,
  Lightbulb,
  Fuel,
  Activity,
  Edit,
  Moon,
  Sun,
  ExternalLink,
} from "lucide-react";

// --- 1. DATA GENERATION (GIỮ NGUYÊN) ---

const SPECS = {
  A: {
    height: "9m",
    floor: "3T/2.5T",
    power: "200 VA/m2",
    desc: "Nhà xưởng xây sẵn (RBF) tiêu chuẩn",
  },
  B: {
    height: "9m",
    floor: "3T/2.5T",
    power: "200 VA/m2",
    desc: "Nhà xưởng xây sẵn (RBF) tiêu chuẩn",
  },
  C: {
    height: "9m",
    floor: "3T/2.5T",
    power: "20 VA/m2",
    desc: "Kho vận Logistics (RBW)",
  },
};

// --- UTILITY DATA ---
const INITIAL_UTILITY_DATA = [
  {
    id: "E-A1-01",
    tenant: "CÔNG TY TNHH SKYWORTH",
    location: "Khu A - T1",
    type: "electricity",
    oldIndex: 1430164,
    newIndex: 1549932,
    lastMonthUsage: 118000,
    images: { old: null, new: null },
  },
  {
    id: "E-A1-02",
    tenant: "CÔNG TY TNHH PONHAN",
    location: "A3-3,4.F1 - A1-1.F1",
    type: "electricity",
    oldIndex: 840091,
    newIndex: 939978,
    lastMonthUsage: 95000,
    images: { old: null, new: null },
  },
  {
    id: "E-A1-03",
    tenant: "CÔNG TY TNHH NEWHENGSENG",
    location: "Khu A - T1",
    type: "electricity",
    oldIndex: 71900,
    newIndex: 83525,
    lastMonthUsage: 12000,
    images: { old: null, new: null },
  },
  {
    id: "E-A1-04",
    tenant: "CÔNG TY TNHH EACH",
    location: "Khu A - T1",
    type: "electricity",
    oldIndex: 156054,
    newIndex: 186409,
    lastMonthUsage: 29000,
    images: { old: null, new: null },
  },
  {
    id: "E-A1-05",
    tenant: "CÔNG TY TNHH MISAN",
    location: "Khu A - T1",
    type: "electricity",
    oldIndex: 70154,
    newIndex: 80143,
    lastMonthUsage: 9500,
    images: { old: null, new: null },
  },
  {
    id: "E-A1-06",
    tenant: "CÔNG TY TNHH JUYUAN",
    location: "Khu A - T1",
    type: "electricity",
    oldIndex: 2066984,
    newIndex: 2245140,
    lastMonthUsage: 180000,
    images: { old: null, new: null },
  },
  {
    id: "PUB-A1",
    tenant: "ĐIỆN CÔNG CỘNG (TRẠM T1)",
    location: "Trạm Biến Áp T1",
    type: "public_elec",
    oldIndex: 3227878,
    newIndex: 3695918,
    lastMonthUsage: 14000,
    images: { old: null, new: null },
    isSystem: true,
  },
  {
    id: "E-A2-01",
    tenant: "CÔNG TY TNHH CÔNG NGHỆ HKC",
    location: "Khu A - T2",
    type: "electricity",
    oldIndex: 4685525,
    newIndex: 5071995,
    lastMonthUsage: 390000,
    images: { old: null, new: null },
  },
  {
    id: "E-A2-02",
    tenant: "CÔNG TY TNHH K&K",
    location: "Khu A - T2",
    type: "electricity",
    oldIndex: 913534,
    newIndex: 946193,
    lastMonthUsage: 31000,
    images: { old: null, new: null },
  },
  {
    id: "E-A2-03",
    tenant: "CÔNG TY ĐIỆN TỬ VAST",
    location: "Khu A - T2",
    type: "electricity",
    oldIndex: 428346,
    newIndex: 443547,
    lastMonthUsage: 14500,
    images: { old: null, new: null },
  },
  {
    id: "E-A2-04",
    tenant: "CÔNG TY TNHH TIETEX VN",
    location: "Khu A - T2",
    type: "electricity",
    oldIndex: 14235,
    newIndex: 14784,
    lastMonthUsage: 500,
    images: { old: null, new: null },
  },
  {
    id: "E-A2-05",
    tenant: "CÔNG TY TNHH GBEST VIỆT NAM",
    location: "Khu A - T2",
    type: "electricity",
    oldIndex: 2417,
    newIndex: 3228,
    lastMonthUsage: 750,
    images: { old: null, new: null },
  },
  {
    id: "E-A2-06",
    tenant: "CÔNG TY TNHH REAK VIỆT NAM",
    location: "Khu A - T2",
    type: "electricity",
    oldIndex: 234469,
    newIndex: 272904,
    lastMonthUsage: 37000,
    images: { old: null, new: null },
  },
  {
    id: "E-A2-07",
    tenant: "CÔNG TY TNHH VOLTA",
    location: "Khu A - T2",
    type: "electricity",
    oldIndex: 59894,
    newIndex: 64749,
    lastMonthUsage: 4900,
    images: { old: null, new: null },
  },
  {
    id: "E-A2-08",
    tenant: "CÔNG TY TNHH HUATEX",
    location: "Khu A - T2",
    type: "electricity",
    oldIndex: 1402439,
    newIndex: 1508963,
    lastMonthUsage: 100000,
    images: { old: null, new: null },
  },
  {
    id: "E-BC-01",
    tenant: "CÔNG TY TNHH CIRCLE LOGISTIC",
    location: "Khu BC",
    type: "electricity",
    oldIndex: 14130,
    newIndex: 15275,
    lastMonthUsage: 1100,
    images: { old: null, new: null },
  },
  {
    id: "E-BC-02",
    tenant: "CÔNG TY NAMTEX",
    location: "Khu BC",
    type: "electricity",
    oldIndex: 16756,
    newIndex: 18021,
    lastMonthUsage: 1200,
    images: { old: null, new: null },
  },
  {
    id: "E-BC-03",
    tenant: "CÔNG TY TNHH SUNTONE",
    location: "Khu BC",
    type: "electricity",
    oldIndex: 51765,
    newIndex: 58216,
    lastMonthUsage: 6500,
    images: { old: null, new: null },
  },
  {
    id: "E-BC-04",
    tenant: "CÔNG TY TNHH CÔNG NGHỆ MTC VN",
    location: "Khu BC",
    type: "electricity",
    oldIndex: 11463793,
    newIndex: 12364007,
    lastMonthUsage: 880000,
    images: { old: null, new: null },
  },
  {
    id: "E-BC-05",
    tenant: "CÔNG TY TNHH CÔNG NGHỆ JIAWEI VN",
    location: "Khu BC",
    type: "electricity",
    oldIndex: 2350976,
    newIndex: 2635289,
    lastMonthUsage: 250000,
    images: { old: null, new: null },
  },
  {
    id: "E-BC-06",
    tenant: "CÔNG TY TNHH TAICHUNG TRAVEL",
    location: "C3-2.F1 - B3-2.F1",
    type: "electricity",
    oldIndex: 232777,
    newIndex: 250991,
    lastMonthUsage: 16000,
    images: { old: null, new: null },
  },
  // Đồng hồ tổng BC
  {
    id: "PUB-BC",
    tenant: "ĐIỆN CÔNG CỘNG KHU BC",
    location: "Trạm Tổng BC",
    type: "public_elec",
    oldIndex: 7732086,
    newIndex: 8923549,
    lastMonthUsage: 10000,
    images: { old: null, new: null },
    isSystem: true,
  },

  // --- KHU A (NƯỚC) ---
  {
    id: "W-A-01",
    tenant: "CÔNG TY TNHH CÔNG NGHỆ HKC",
    location: "Khu A",
    type: "water",
    oldIndex: 24843,
    newIndex: 28098,
    lastMonthUsage: 3100,
    images: { old: null, new: null },
  },
  {
    id: "W-A-02",
    tenant: "CÔNG TY TNHH K&K",
    location: "Khu A",
    type: "water",
    oldIndex: 3355,
    newIndex: 3449,
    lastMonthUsage: 90,
    images: { old: null, new: null },
  },
  {
    id: "W-A-03",
    tenant: "CÔNG TY ĐIỆN TỬ VAST",
    location: "Khu A",
    type: "water",
    oldIndex: 719,
    newIndex: 750,
    lastMonthUsage: 30,
    images: { old: null, new: null },
  },
  {
    id: "W-A-04",
    tenant: "CÔNG TY TNHH MISAN VINA",
    location: "Khu A",
    type: "water",
    oldIndex: 309,
    newIndex: 343,
    lastMonthUsage: 35,
    images: { old: null, new: null },
  },
  {
    id: "W-A-05",
    tenant: "CÔNG TY TNHH TIETEX VN",
    location: "Khu A",
    type: "water",
    oldIndex: 433,
    newIndex: 455,
    lastMonthUsage: 20,
    images: { old: null, new: null },
  },
  {
    id: "W-A-06",
    tenant: "CÔNG TY TNHH REAK VIỆT NAM",
    location: "Khu A",
    type: "water",
    oldIndex: 2817,
    newIndex: 3166,
    lastMonthUsage: 340,
    images: { old: null, new: null },
  },
  {
    id: "W-A-07",
    tenant: "CÔNG TY TNHH GBEST VIỆT NAM",
    location: "Khu A",
    type: "water",
    oldIndex: 227,
    newIndex: 241,
    lastMonthUsage: 15,
    images: { old: null, new: null },
  },
  {
    id: "W-A-08",
    tenant: "CÔNG TY TNHH HUATEX",
    location: "Khu A",
    type: "water",
    oldIndex: 4117,
    newIndex: 4471,
    lastMonthUsage: 360,
    images: { old: null, new: null },
  },
  {
    id: "W-A-09",
    tenant: "CÔNG TY TNHH VOLTA",
    location: "Khu A",
    type: "water",
    oldIndex: 837,
    newIndex: 855,
    lastMonthUsage: 18,
    images: { old: null, new: null },
  },

  // --- KHU BC (NƯỚC) ---
  {
    id: "W-BC-01",
    tenant: "CÔNG TY SUNTONE",
    location: "Khu BC",
    type: "water",
    oldIndex: 884,
    newIndex: 918,
    lastMonthUsage: 30,
    images: { old: null, new: null },
  },
  {
    id: "W-BC-02",
    tenant: "CÔNG TY TNHH NAMTEX",
    location: "Khu BC",
    type: "water",
    oldIndex: 40,
    newIndex: 41,
    lastMonthUsage: 1,
    images: { old: null, new: null },
  },
  {
    id: "W-BC-03",
    tenant: "CÔNG TY TNHH CIRCLE LOGISTIC",
    location: "Khu BC",
    type: "water",
    oldIndex: 94,
    newIndex: 101,
    lastMonthUsage: 5,
    images: { old: null, new: null },
  },
  {
    id: "W-BC-04",
    tenant: "CÔNG TY TNHH CÔNG NGHỆ MTC VN",
    location: "Khu BC",
    type: "water",
    oldIndex: 64392,
    newIndex: 72351,
    lastMonthUsage: 7900,
    images: { old: null, new: null },
  },
  {
    id: "W-BC-05",
    tenant: "CÔNG TY TNHH CÔNG NGHỆ JIAWEI VN",
    location: "Khu BC",
    type: "water",
    oldIndex: 7465,
    newIndex: 7939,
    lastMonthUsage: 480,
    images: { old: null, new: null },
  },
  {
    id: "W-BC-06",
    tenant: "CÔNG TY TNHH TAICHUNG TRAVEL",
    location: "Khu BC",
    type: "water",
    oldIndex: 3649,
    newIndex: 3791,
    lastMonthUsage: 140,
    images: { old: null, new: null },
  },
  // Đồng hồ tổng nước
  {
    id: "PUB-W-BC",
    tenant: "NƯỚC CÔNG CỘNG KHU BC",
    location: "Đồng hồ tổng",
    type: "public_water",
    oldIndex: 134975,
    newIndex: 147584,
    lastMonthUsage: 12000,
    images: { old: null, new: null },
    isSystem: true,
  },
];

// --- FUEL DATA (FROM UPLOADED FILES) ---
const INITIAL_FUEL_DATA = [
  {
    id: "F-A-01",
    name: "Bơm diesel PCCC khu A",
    location: "Trạm bơm khu A",
    capacity: 1500,
    current: 1120,
    lastRefuel: "2025-11-07",
    lastRefuelAmount: 30,
    type: "pump",
    logs: [
      {
        date: "2025-10-03",
        type: "run",
        startTime: "09:30",
        endTime: "10:00",
        duration: 30,
        consumption: 30,
        operator: "Hoàng",
        note: "Chạy định kỳ",
        images: [],
      },
      {
        date: "2025-10-10",
        type: "run",
        startTime: "09:25",
        endTime: "09:55",
        duration: 30,
        consumption: 30,
        operator: "Đô",
        note: "Chạy định kỳ",
        images: [],
      },
      {
        date: "2025-10-17",
        type: "run",
        startTime: "09:42",
        endTime: "10:12",
        duration: 30,
        consumption: 30,
        operator: "Khải",
        note: "Chạy định kỳ",
        images: [],
      },
      {
        date: "2025-10-24",
        type: "run",
        startTime: "09:40",
        endTime: "10:10",
        duration: 30,
        consumption: 30,
        operator: "Hải",
        note: "Chạy định kỳ",
        images: [],
      },
    ],
  },
  {
    id: "F-A-02",
    name: "Máy phát điện A1",
    location: "Trạm MSB#1",
    capacity: 600,
    current: 495,
    lastRefuel: "2025-11-07",
    lastRefuelAmount: 10,
    type: "generator",
    logs: [],
  },
  {
    id: "F-A-03",
    name: "Máy phát điện A2",
    location: "Trạm MSB#2",
    capacity: 600,
    current: 485,
    lastRefuel: "2025-11-07",
    lastRefuelAmount: 10,
    type: "generator",
    logs: [],
  },
  {
    id: "F-A-04",
    name: "Máy phát điện A3",
    location: "Trạm MSB#3",
    capacity: 500,
    current: 474,
    lastRefuel: "2025-11-07",
    lastRefuelAmount: 10,
    type: "generator",
    logs: [],
  },
  {
    id: "F-A-05",
    name: "Máy phát điện A4",
    location: "Trạm MSB#4",
    capacity: 500,
    current: 502,
    lastRefuel: "2025-11-07",
    lastRefuelAmount: 10,
    type: "generator",
    logs: [],
  },
  {
    id: "F-BC-01",
    name: "Bơm diesel PCCC khu BC",
    location: "Trạm bơm khu BC",
    capacity: 1500,
    current: 1060,
    lastRefuel: "2025-11-07",
    lastRefuelAmount: 30,
    type: "pump",
    logs: [
      {
        date: "2025-10-03",
        type: "run",
        startTime: "08:38",
        endTime: "08:53",
        duration: 15,
        consumption: 4,
        operator: "Hải",
        note: "Chạy định kỳ",
        images: [],
      },
      {
        date: "2025-10-10",
        type: "run",
        startTime: "08:45",
        endTime: "09:00",
        duration: 15,
        consumption: 4,
        operator: "Hải",
        note: "Chạy định kỳ",
        images: [],
      },
    ],
  },
  {
    id: "F-BC-02",
    name: "Máy phát điện C1-1",
    location: "Trạm MSB#7",
    capacity: 200,
    current: 177,
    lastRefuel: "2025-11-07",
    lastRefuelAmount: 10,
    type: "generator",
    logs: [],
  },
  {
    id: "F-BC-03",
    name: "Máy phát điện C3-1",
    location: "Trạm MSB#2",
    capacity: 255,
    current: 148,
    lastRefuel: "2025-11-07",
    lastRefuelAmount: 10,
    type: "generator",
    logs: [],
  },
  {
    id: "F-BC-04",
    name: "Máy phát điện C3-4",
    location: "Trạm MSB#1",
    capacity: 255,
    current: 223,
    lastRefuel: "2025-11-07",
    lastRefuelAmount: 10,
    type: "generator",
    logs: [],
  },
];

// --- SHARED DATA ---
const MAINTENANCE_CATEGORIES = [
  {
    id: "infra",
    label: "Hạ Tầng & Kiến Trúc",
    sub: [
      "Sàn bê tông / Epoxy",
      "Tường / Vách ngăn",
      "Cửa cuốn / Dock Leveler",
      "Mái / Chống thấm",
      "Trần / Cách nhiệt",
    ],
  },
  {
    id: "me",
    label: "Hệ Thống Cơ Điện (M&E)",
    sub: [
      "Hệ thống chiếu sáng",
      "Tủ điện / Máy biến áp",
      "Cấp thoát nước",
      "Quạt thông gió",
    ],
  },
  {
    id: "pccc",
    label: "An Toàn & PCCC",
    sub: [
      "Hệ thống báo cháy",
      "Đầu phun Sprinkler",
      "Bình chữa cháy",
      "Lối thoát hiểm",
    ],
  },
  {
    id: "landscape",
    label: "Cảnh Quan & Tiện Ích",
    sub: [
      "Đường nội bộ",
      "Cây xanh / Vệ sinh",
      "Hàng rào / Cổng",
      "Nhà bảo vệ",
    ],
  },
];

const SUPPORT_CATEGORIES = [
  "Điện (Electricity)",
  "Nước (Water)",
  "Internet / Viễn thông",
  "An ninh / Bảo vệ",
  "Vệ sinh / Cảnh quan",
  "Thủ tục / Giấy tờ",
  "Khác",
];

// Mock Data
const MAINTENANCE_TICKETS = [
  {
    id: "MT-001",
    date: "2024-10-15",
    unitId: "A4-1.F1",
    category: "Hạ Tầng & Kiến Trúc",
    subCategory: "Cửa cuốn / Dock Leveler",
    desc: "Cửa cuốn số 2 bị kẹt, motor kêu to.",
    status: "completed",
    priority: "high",
    reporter: "Nguyễn Văn A (BQL)",
  },
  {
    id: "MT-002",
    date: "2024-10-20",
    unitId: "C3-1.F1",
    category: "Hệ Thống Cơ Điện (M&E)",
    subCategory: "Hệ thống chiếu sáng",
    desc: "Dãy đèn LED khu vực kho lạnh bị nhấp nháy.",
    status: "processing",
    priority: "medium",
    reporter: "Trần Thị B (Tenant)",
  },
  {
    id: "MT-003",
    date: "2024-11-02",
    unitId: "B2-1.F2",
    category: "An Toàn & PCCC",
    subCategory: "Đầu phun Sprinkler",
    desc: "Rò rỉ nước nhẹ tại đầu phun khu vực hành lang.",
    status: "new",
    priority: "critical",
    reporter: "Lê Văn C (Bảo vệ)",
  },
  {
    id: "MT-004",
    date: "2024-11-05",
    unitId: "A2-3.F1",
    category: "Hạ Tầng & Kiến Trúc",
    subCategory: "Sàn bê tông / Epoxy",
    desc: "Sàn bị nứt chân chim khu vực xe nâng đi qua.",
    status: "new",
    priority: "low",
    reporter: "Phạm D (Kỹ thuật)",
  },
];

const SUPPORT_TICKETS = [
  {
    id: "REQ-001",
    title: "Mất điện cục bộ khu vực chuyền 2",
    type: "emergency",
    category: "Điện (Electricity)",
    status: "in_progress",
    progress: 65,
    eta: "14:30 Hôm nay",
    created: "2025-11-22 10:00",
    location: "A4-1.F1",
    description: "Aptomat tổng tự ngắt, có mùi khét nhẹ.",
    feedback: null,
    rating: 0,
    images: { before: null, during: null, after: null },
  },
  {
    id: "REQ-002",
    title: "Vòi nước nhà vệ sinh nam bị rò rỉ",
    type: "medium",
    category: "Nước (Water)",
    status: "pending",
    progress: 0,
    eta: "Chưa xác định",
    created: "2025-11-22 09:15",
    location: "C3-2.F1",
    description: "Nước chảy yếu nhưng không ngắt được.",
    feedback: null,
    rating: 0,
    images: { before: null, during: null, after: null },
  },
  {
    id: "REQ-003",
    title: "Thay bóng đèn cao áp đường nội bộ",
    type: "low",
    category: "Vệ sinh / Cảnh quan",
    status: "completed",
    progress: 100,
    eta: "Đã hoàn thành",
    created: "2025-11-20 14:00",
    location: "Đường D2",
    description: "Đèn số 15 bị nhấp nháy.",
    feedback: "Thợ làm nhanh, nhiệt tình.",
    rating: 5,
    images: { before: null, during: null, after: null },
  },
];

const NOTICES = [
  {
    id: 1,
    type: "maintenance",
    title: "Bảo trì trạm biến áp T2",
    date: "25/11/2025",
    time: "08:00 - 12:00",
    desc: "Cắt điện toàn bộ khu B để bảo dưỡng định kỳ.",
  },
  {
    id: 2,
    type: "payment",
    title: "Nhắc hạn thanh toán phí QL",
    date: "30/11/2025",
    time: "Hạn chót",
    desc: "Vui lòng thanh toán phí quản lý tháng 11.",
  },
  {
    id: 3,
    type: "legal",
    title: "Gia hạn giấy phép PCCC",
    date: "15/12/2025",
    time: "Sắp hết hạn",
    desc: "Giấy chứng nhận PCCC của Unit A4-1 sắp hết hạn.",
  },
];
